package minio

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/vault/sdk/framework"
	"github.com/hashicorp/vault/sdk/logical"
)

var (
	ErrRoleNotFound = errors.New("role not found")
)

const (
	StaticCredentialType = "static"
	StsCredentialType    = "sts"
)

// A role stored in the storage backend
type Role struct {

	// PolicyName is the policy to be attached when creating user static credential
	PolicyName string `json:"policy_name"`

	// Type of credential created
	CredentialType string `json:"credential_type"`

	// UserNamePrefix is what we prepend to the user static access key
	// followed by the Vault request ID
	UserNamePrefix string `json:"user_name_prefix,omitempty"`

	// MaxStsTTL is the maximum TTL that STS token can exist before it expires for this role
	MaxStsTTL string `json:"max_sts_ttl"`

	// MaxTTL is the maximum TTL for static credential to exist after which new ones are created
	MaxTTL string `json:"max_ttl"`

	// Grace period applied to credentials after their max ttl before being deleted
	GracePeriod string `json:"grace_period"`
}

// List the defined roles
func (b *minioBackend) pathRoles() *framework.Path {
	return &framework.Path{
		Pattern:      fmt.Sprintf("roles/?"),
		HelpSynopsis: "List configured roles.",

		Operations: map[logical.Operation]framework.OperationHandler{
			logical.ListOperation: &framework.PathOperation{
				Callback: b.pathRolesList,
			},
		},
	}
}

// pathRolesList lists the currently defined roles
func (b *minioBackend) pathRolesList(ctx context.Context, req *logical.Request, _ *framework.FieldData) (*logical.Response, error) {
	b.Logger().Info("Listing all roles stored in vault!")
	roles, err := b.ListRoles(ctx, req.Storage)

	if err != nil {
		b.Logger().Error("failed to list roles!", err)
		return nil, err
	}

	return logical.ListResponse(roles), nil
}

// Define the CRUD functions for the roles path
func (b *minioBackend) pathRolesCRUD() *framework.Path {
	return &framework.Path{
		Pattern:         "roles/" + framework.GenericNameRegex("role"),
		HelpSynopsis:    "Configure a Minio user role.",
		HelpDescription: "Use this endpoint to set the police for generated user in this role.",

		Fields: map[string]*framework.FieldSchema{
			"role": &framework.FieldSchema{
				Type:        framework.TypeString,
				Description: "Role name.",
			},
			"user_name_prefix": &framework.FieldSchema{
				Type:        framework.TypeString,
				Description: "Prefix for static user access key generated by this role.",
			},
			"policy_name": &framework.FieldSchema{
				Type:        framework.TypeString,
				Description: "Minio policy name to attach static credentials.",
			},
			"credential_type": &framework.FieldSchema{
				Type:        framework.TypeString,
				Description: "Type of credential created.",
			},
			"max_sts_ttl": &framework.FieldSchema{
				Type:        framework.TypeString,
				Default:     "24h",
				Description: "Maximum TTL applied to sts token keys.",
			},
			"max_ttl": &framework.FieldSchema{
				Type:        framework.TypeString,
				Default:     "720h",
				Description: "Maximum TTL applied to static credential.",
			},
			"grace_period": &framework.FieldSchema{
				Type:        framework.TypeString,
				Default:     "24h",
				Description: "Grace period applied to credentials after their max ttl before being deleted",
			},
		},

		ExistenceCheck: b.pathRoleExistsCheck,

		Operations: map[logical.Operation]framework.OperationHandler{
			logical.CreateOperation: &framework.PathOperation{
				Callback: b.pathRoleWrite,
			},
			logical.ReadOperation: &framework.PathOperation{
				Callback: b.pathRoleRead,
			},
			logical.UpdateOperation: &framework.PathOperation{
				Callback: b.pathRoleWrite,
			},
			logical.DeleteOperation: &framework.PathOperation{
				Callback: b.pathRoleDelete,
			},
		},
	}
}

// pathRoleExistsCheck checks to see if a role exists
func (b *minioBackend) pathRoleExistsCheck(ctx context.Context, req *logical.Request, d *framework.FieldData) (bool, error) {
	role := d.Get("role").(string)
	if r, err := b.GetRole(ctx, req.Storage, role); err != nil || r == nil {
		return false, nil
	}

	return true, nil
}

// pathRoleRead reads information on a current role
func (b *minioBackend) pathRoleRead(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	role := d.Get("role").(string)
	b.Logger().Info("Retrieving role " + role + " details stored in vault!")
	r, err := b.GetRole(ctx, req.Storage, role)

	if err != nil {
		if err == ErrRoleNotFound {
			return logical.ErrorResponse(err.Error()), logical.ErrInvalidRequest
		}
		b.Logger().Error("failed to get role details", err)
		return nil, err
	}
	role_data := map[string]interface{}{
		"user_name_prefix": r.UserNamePrefix,
		"policy_name":      r.PolicyName,
		"max_ttl":          r.MaxTTL,
		"grace_period":     r.GracePeriod,
		"credential_type":  r.CredentialType,
	}
	if r.CredentialType == StsCredentialType {
		role_data["max_sts_ttl"] = r.MaxStsTTL
	}

	return &logical.Response{
		Data: role_data,
	}, nil
}

// pathRoleWrite creates/updates a role entry
func (b *minioBackend) pathRoleWrite(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	role := d.Get("role").(string)
	b.Logger().Info("Writing role " + role + " in vault!")

	var r Role
	r.CredentialType = d.Get("credential_type").(string)
	r.PolicyName = d.Get("policy_name").(string)
	r.UserNamePrefix = d.Get("user_name_prefix").(string)
	r.MaxTTL = d.Get("max_ttl").(string)
	r.GracePeriod = d.Get("grace_period").(string)
	if r.CredentialType == StsCredentialType {
		r.MaxStsTTL = d.Get("max_sts_ttl").(string)
	}

	entry, err := logical.StorageEntryJSON("roles/"+role, &r)
	if err != nil {
		b.Logger().Error("failed to create storage entry when updating role!", err)
		return nil, fmt.Errorf("failed to create storage entry: %v", err)
	}

	if err := req.Storage.Put(ctx, entry); err != nil {
		b.Logger().Error("failed to write entry to storage when updating role!", err)
		return nil, fmt.Errorf("failed to write entry to storage: %v", err)
	}

	return nil, nil
}

// pathRoleDelete deletes a role
func (b *minioBackend) pathRoleDelete(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
	b.Logger().Info("Deleting role from in vault!")
	roleName := d.Get("role").(string)
	r, err := b.GetRole(ctx, req.Storage, roleName)
	if err != nil {
		b.Logger().Error("error in getting role", err)
		return nil, err
	}
	b.Logger().Info("Removing all credentials from vault and minio for " + roleName)
	// Remove all user credentials and expired credentials
	err = b.removeAllUserCreds(ctx, req, r, roleName)
	if err != nil {
		b.Logger().Error("failed to remove all user credentials when deleting role", err)
		return nil, err
	}
	if err = req.Storage.Delete(ctx, "roles/"+roleName); err != nil {
		b.Logger().Error("failed to delete role from storage!", err)
		return nil, fmt.Errorf("failed to delete role from storage: %v", err)
	}

	return nil, nil
}

func (b *minioBackend) ListRoles(ctx context.Context, s logical.Storage) ([]string, error) {
	roles, err := s.List(ctx, "roles/")
	if err != nil {
		b.Logger().Error("unable to retrieve list of roles!", err)
		return nil, fmt.Errorf("unable to retrieve list of roles: %v", err)
	}

	return roles, nil
}
func (b *minioBackend) GetRole(ctx context.Context, s logical.Storage, role string) (*Role, error) {
	r, err := s.Get(ctx, "roles/"+role)
	if err != nil {
		b.Logger().Error("unable to retrieve role", err)
		return nil, fmt.Errorf("unable to retrieve role %v %v", role, err)
	}

	if r == nil {
		return nil, ErrRoleNotFound
	}

	var rv Role
	if err := r.DecodeJSON(&rv); err != nil {
		b.Logger().Error("unable to decode role!", err)
		return nil, fmt.Errorf("unable to decode role %v: %v", role, err)
	}

	return &rv, nil
}
